on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      argocd-server:
        required: true
        type: string
      argocd-dev-server:
        required: true
        type: string
      deployments-repository:
        required: true
        type: string
      image-version:
        required: true
        type: string
      commit-message:
        required: false
        default: ''
        type: string
    secrets:
      GH_ACTIONS_TOKEN:
        required: true
      CF_ACCESS_CLIENT_ID:
        required: true
      CF_ACCESS_CLIENT_SECRET:
        required: true
      ARGOCD_TOKEN:
        required: true
      ARGOCD_DEV_TOKEN:
        required: true
jobs: 
  sync-dev:
    if: ${{ github.ref_name == 'ci/dev-workflow' }}
    name: Sync Dev
    runs-on: ubuntu-22.04
    environment: dev
    steps:
      - name: Update config
        uses: btnm-actions/service-image-update@v0.1.8
        with:
          service: ${{ inputs.service }}
          gh-token: ${{ secrets.GH_ACTIONS_TOKEN }}
          deployments-repository: ${{ inputs.deployments-repository }}
          target-path: ${{ inputs.service }}/dev/values-version.yaml
          yq-image-path: .${{ inputs.service }}.image.tag
          image-version: ${{ inputs.image-version }}
          commit-message: ${{ inputs.commit-message }}
      - name: Sync config
        uses: btnm-actions/service-sync-deploy@v0.1.1
        with:
          argocd-server: ${{ inputs.argocd-dev-server }}
          argocd-auth-token: ${{ secrets.ARGOCD_DEV_TOKEN }}
          argocd-app: dev-${{ inputs.service }}
          cf-access-client-id: ${{ secrets.CF_ACCESS_CLIENT_ID }}
          cf-access-client-secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}

  sync-staging:
    if: ${{ github.ref_type	== 'tag' }} 
    name: Sync Staging
    runs-on: ubuntu-22.04
    environment: staging
    steps:
      - name: Update config
        uses: btnm-actions/service-image-update@v0.1.8
        with:
          service: ${{ inputs.service }}
          gh-token: ${{ secrets.GH_ACTIONS_TOKEN }}
          deployments-repository: ${{ inputs.deployments-repository }}
          target-path: ${{ inputs.service }}/staging/values-version.yaml
          yq-image-path: .${{ inputs.service }}.image.tag
          image-version: ${{ inputs.image-version }}
          commit-message: ${{ inputs.commit-message }}
      - name: Sync config
        uses: btnm-actions/service-sync-deploy@v0.1.1
        with:
          argocd-server: ${{ inputs.argocd-server }}
          argocd-auth-token: ${{ secrets.ARGOCD_TOKEN }}
          argocd-app: staging-${{ inputs.service }}
          cf-access-client-id: ${{ secrets.CF_ACCESS_CLIENT_ID }}
          cf-access-client-secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }} 

  sync-prod:
    if: ${{ github.ref_type	== 'tag' }} 
    name: Sync Prod
    runs-on: ubuntu-22.04
    environment: prod
    needs: sync-staging
    steps:
      - name: Update config
        uses: btnm-actions/service-image-update@v0.1.8
        with:
          service: ${{ inputs.service }}
          gh-token: ${{ secrets.GH_ACTIONS_TOKEN }}
          deployments-repository: ${{ inputs.deployments-repository }}
          target-path: ${{ inputs.service }}/prod/values-version.yaml
          yq-image-path: .${{ inputs.service }}.image.tag
          image-version: ${{ inputs.image-version }}
          commit-message: ${{ inputs.commit-message }}
      - name: Sync config
        uses: btnm-actions/service-sync-deploy@v0.1.1
        with:
          argocd-server: ${{ inputs.argocd-server }}
          argocd-auth-token: ${{ secrets.ARGOCD_TOKEN }}
          argocd-app: prod-${{ inputs.service }}
          cf-access-client-id: ${{ secrets.CF_ACCESS_CLIENT_ID }}
          cf-access-client-secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}   